<!--
%\VignetteEngine{knitr::docco_linear}
%\VignetteIndexEntry{The archivist package compendium}
-->

# The archivist package compendium

## Archiving artifacts with their chaining code

Some text about package
```{r, message=FALSE,comment="", warning=FALSE}
library(archivist)
exampleRepoDir <- getwd()
createEmptyRepo( exampleRepoDir )
```

```{r, message=FALSE,comment="", warning=FALSE}
# example 1
library(dplyr)

data("hflights", package = "hflights")
hflights %>%
   group_by(Year, Month, DayofMonth) %>%
   select(Year:DayofMonth, ArrDelay, DepDelay) %>%
   summarise(
      arr = mean(ArrDelay, na.rm = TRUE),
      dep = mean(DepDelay, na.rm = TRUE)
   ) %>%
   filter(arr > 30 | dep > 30) %>%
   saveToRepo( exampleRepoDir )  
```

```{r, message=FALSE,comment="", warning=FALSE}
# example 2
library(Lahman)

#players <- group_by(Batting, playerID)
#games <- summarise(players, total = sum(G))
#head(arrange(games, desc(total)), 5)


Batting %.%
   group_by(playerID) %.%
   summarise(total = sum(G)) %.%
   arrange(desc(total)) %.%
   head(5) %>%
   saveToRepo( exampleRepoDir )
```

```{r, message=FALSE,comment="", warning=FALSE}
# example 3
crime.by.state <- read.csv("CrimeStatebyState.csv")
crime.by.state %.%
   filter(State=="New York", Year==2005) %.%
   arrange(desc(Count)) %.%
   select(Type.of.Crime, Count) %.%
   mutate(Proportion=Count/sum(Count)) %.%
   group_by(Type.of.Crime) %.%
   summarise(num.types = n(), counts = sum(Count)) %>%
   saveToRepo( exampleRepoDir )
```

```{r, message=FALSE,comment="", warning=FALSE}
# example 4
library(ggplot2)

diamonds %.% # start by specifying the data.frame
   group_by(cut, clarity, color) %.%  # The specify the grouping variables
   summarize(
      meancarat = mean(carat, na.rm = TRUE), 
      ndiamonds = length(carat)
   ) %>%
head( 10) %>%
   saveToRepo( exampleRepoDir )
```

```{r, message=FALSE,comment="", warning=FALSE}
# example 5
data(mtcars)
mtcars %.% 
   group_by(cyl, am) %.%
   select(mpg, cyl, wt, am) %.%
   summarise(avgmpg = mean(mpg), avgwt = mean(wt)) %.%
   filter(avgmpg > 20) %>%
   saveToRepo( exampleRepoDir )

```

```{r, message=FALSE,comment="", warning=FALSE}
# summary
showLocalRepo( exampleRepoDir )[, 2]
showLocalRepo( exampleRepoDir, "tags" )[,-3]
summaryLocalRepo( exampleRepoDir )

```




